name: Upload Python Package to PyPI

on:
  # Trigger the workflow when a new release is created in GitHub
  release:
    types: [published]
  # Or, trigger it manually from the Actions tab
  workflow_dispatch:

permissions:
  # This permission is required for trusted publishing
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # The 'user' and 'password' fields are not needed because of trusted publishing
        # The action will automatically get a short-lived token from PyPI
        # and use it to authenticate.
        packages_dir: dist/
